// commandr/frontend-vue-backup/src/App.vue
// 1. App.vue - Main layout
<script setup lang="ts">
import { ref } from 'vue'
import ChatInput from './components/ChatInput.vue'
import ChatWindow from './components/ChatWindow.vue'
import SettingsButton from './components/SettingsButton.vue'
import { useMessages } from './composables/useMessages'
import { useSettings } from './composables/useSettings'
import { cohereTheme } from './styles/theme'

const { messages, addMessage } = useMessages()
const { settings } = useSettings()
const isLoading = ref(false)

const handleSendMessage = async (content: string) => {
  isLoading.value = true
  try {
    await addMessage(content, settings.value.temperature)
  } finally {
    isLoading.value = false
  }
}
</script>

<template>
  <div class="app-container">
    <header class="app-header">
      <h1>CommandR</h1>
      <SettingsButton />
    </header>
    
    <main class="chat-container">
      <ChatWindow 
        :messages="messages" 
        :isLoading="isLoading" 
      />
      <ChatInput 
        @send="handleSendMessage"
        :isLoading="isLoading"
      />
    </main>
  </div>
</template>

<style scoped>
.app-container {
  height: 100vh;
  display: flex;
  flex-direction: column;
  background-color: v-bind('cohereTheme.colors.background.DEFAULT');
}

.app-header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: v-bind('cohereTheme.spacing.md') v-bind('cohereTheme.spacing.lg');
  border-bottom: 1px solid v-bind('cohereTheme.colors.border.DEFAULT');
}

.app-header h1 {
  font-size: 1.25rem;
  font-weight: 600;
  color: v-bind('cohereTheme.colors.text.primary');
}

.chat-container {
  flex: 1;
  display: flex;
  flex-direction: column;
  overflow: hidden;
}
</style>

// commandr/frontend/src/App.tsx
import ChatWindow from './components/ChatWindow';
import ChatInput from './components/ChatInput';
import { useMessages } from './hooks/useMessages';
import './App.css';

function App() {
  const { messages, isLoading, addMessage, clearMessages } = useMessages();

  const handleSendMessage = (content: string) => {
    addMessage(content);
  };

  const handleClearChat = () => {
    clearMessages();
  };

  return (
    <div className="h-screen flex flex-col bg-gray-50">
      {/* Header */}
      <header className="bg-white border-b border-gray-200 px-6 py-4 flex items-center justify-between">
        <h1 className="text-xl font-semibold text-gray-900">CommandR</h1>
        <button
          onClick={handleClearChat}
          className="px-3 py-1 text-sm text-gray-600 hover:text-gray-900 border border-gray-300 rounded hover:bg-gray-50 transition-colors"
        >
          Clear Chat
        </button>
      </header>

      {/* Chat Area */}
      <main className="flex-1 flex flex-col overflow-hidden">
        <ChatWindow messages={messages} isLoading={isLoading} />
        <ChatInput onSend={handleSendMessage} isLoading={isLoading} />
      </main>
    </div>
  );
}

export default App;
